"""add_inquiries_and_seo_fields

Revision ID: 00cc4d88d3b7
Revises: 0d446d048260
Create Date: 2026-02-15 22:52:25.880620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cc4d88d3b7'
down_revision: Union[str, None] = '0d446d048260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('course_interested', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_inquiries_id'), 'inquiries', ['id'], unique=False)
    op.add_column('pages', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('pages', sa.Column('meta_keywords', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('canonical_url', sa.String(length=500), nullable=True))
    op.add_column('pages', sa.Column('robots', sa.String(length=100), nullable=True))
    op.add_column('pages', sa.Column('og_title', sa.String(length=255), nullable=True))
    op.add_column('pages', sa.Column('og_description', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('og_image', sa.String(length=500), nullable=True))
    op.add_column('pages', sa.Column('twitter_title', sa.String(length=255), nullable=True))
    op.add_column('pages', sa.Column('twitter_description', sa.Text(), nullable=True))
    op.add_column('pages', sa.Column('twitter_image', sa.String(length=500), nullable=True))
    op.add_column('pages', sa.Column('schema_markup', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'schema_markup')
    op.drop_column('pages', 'twitter_image')
    op.drop_column('pages', 'twitter_description')
    op.drop_column('pages', 'twitter_title')
    op.drop_column('pages', 'og_image')
    op.drop_column('pages', 'og_description')
    op.drop_column('pages', 'og_title')
    op.drop_column('pages', 'robots')
    op.drop_column('pages', 'canonical_url')
    op.drop_column('pages', 'meta_keywords')
    op.drop_column('pages', 'meta_title')
    op.drop_index(op.f('ix_inquiries_id'), table_name='inquiries')
    op.drop_table('inquiries')
    # ### end Alembic commands ###
