"""Add is_read and admin_notes to Inquiries

Revision ID: 0c502aa25b7e
Revises: 00cc4d88d3b7
Create Date: 2026-02-15 23:06:55.165005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c502aa25b7e'
down_revision: Union[str, None] = '00cc4d88d3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('inquiries', sa.Column('admin_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquiries', 'admin_notes')
    op.drop_column('inquiries', 'is_read')
    # ### end Alembic commands ###
