"""add activity slug/short_description/content_html/thumbnail_image

Revision ID: 0d141484e21d
Revises: 68829fcb6e68
Create Date: 2026-02-22 13:13:52.950147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d141484e21d'
down_revision: Union[str, None] = '68829fcb6e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('slug', sa.String(length=100), nullable=True))
    op.add_column('activities', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('activities', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('activities', sa.Column('thumbnail_image', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_activities_slug'), 'activities', ['slug'], unique=False)
    op.drop_column('activities', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_activities_slug'), table_name='activities')
    op.drop_column('activities', 'thumbnail_image')
    op.drop_column('activities', 'content_html')
    op.drop_column('activities', 'short_description')
    op.drop_column('activities', 'slug')
    # ### end Alembic commands ###
