"""add_sort_order_to_faculty

Revision ID: 22cfdbf0360d
Revises: c405526e6a5a
Create Date: 2026-06-26 12:16:32.830118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cfdbf0360d'
down_revision: Union[str, None] = 'c405526e6a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculties', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculties', 'sort_order')
    # ### end Alembic commands ###
