"""add_footer_logo_and_document_download_link_to_colleges

Revision ID: 2703c5092f11
Revises: fb6e9374efb7
Create Date: 2026-03-04 00:05:51.906611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2703c5092f11'
down_revision: Union[str, None] = 'fb6e9374efb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('footer_logo', sa.String(length=500), nullable=True))
    op.add_column('colleges', sa.Column('document_download_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colleges', 'document_download_link')
    op.drop_column('colleges', 'footer_logo')
    # ### end Alembic commands ###
