"""initial_schema

Revision ID: 2c68f889a189
Revises: 0d141484e21d
Create Date: 2026-02-24 18:22:13.654388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c68f889a189'
down_revision: Union[str, None] = '0d141484e21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'thumbnail_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('thumbnail_image', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
