"""Add logo_url to Journal

Revision ID: 459122eeffe2
Revises: 8b67005f7c57
Create Date: 2026-06-25 12:43:22.151209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459122eeffe2'
down_revision: Union[str, None] = '8b67005f7c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'logo_url')
    # ### end Alembic commands ###
