"""add_gallery_images_to_news

Revision ID: 59fd10a67dee
Revises: 10834c9ff6b1
Create Date: 2026-02-28 17:32:16.511063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fd10a67dee'
down_revision: Union[str, None] = '10834c9ff6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('gallery_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'gallery_images')
    # ### end Alembic commands ###
