"""Add JournalVolume model

Revision ID: 5d804863fe54
Revises: b041a3f18fa5
Create Date: 2026-06-25 11:55:17.149772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d804863fe54'
down_revision: Union[str, None] = 'b041a3f18fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('journal_name', sa.String(length=255), nullable=True),
    sa.Column('volume_title', sa.String(length=255), nullable=False),
    sa.Column('editorial_link', sa.String(length=500), nullable=True),
    sa.Column('contents_link', sa.String(length=500), nullable=True),
    sa.Column('papers', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_journal_volumes_id'), 'journal_volumes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_volumes_id'), table_name='journal_volumes')
    op.drop_table('journal_volumes')
    # ### end Alembic commands ###
