"""Add Journal model for static pages and update JournalVolume

Revision ID: 8b67005f7c57
Revises: 5d804863fe54
Create Date: 2026-06-25 12:10:51.596634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b67005f7c57'
down_revision: Union[str, None] = '5d804863fe54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('about_html', sa.Text(), nullable=True),
    sa.Column('call_for_papers_html', sa.Text(), nullable=True),
    sa.Column('policies_html', sa.Text(), nullable=True),
    sa.Column('author_guidelines_html', sa.Text(), nullable=True),
    sa.Column('contact_us_html', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_journals_id'), 'journals', ['id'], unique=False)
    op.add_column('journal_volumes', sa.Column('journal_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'journal_volumes', 'journals', ['journal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('journal_volumes', 'journal_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_volumes', sa.Column('journal_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'journal_volumes', type_='foreignkey')
    op.drop_column('journal_volumes', 'journal_id')
    op.drop_index(op.f('ix_journals_id'), table_name='journals')
    op.drop_table('journals')
    # ### end Alembic commands ###
