"""Add description to faculty

Revision ID: 9ccb8d6c6bb7
Revises: 0c502aa25b7e
Create Date: 2026-02-15 23:42:23.979314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ccb8d6c6bb7'
down_revision: Union[str, None] = '0c502aa25b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculties', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculties', 'description')
    # ### end Alembic commands ###
