"""added crmsyncing

Revision ID: b041a3f18fa5
Revises: meritto_crm_sync_audit
Create Date: 2026-04-06 00:50:16.678620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b041a3f18fa5'
down_revision: Union[str, None] = 'meritto_crm_sync_audit'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meritto_crm_sync_audit', 'entity_type',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=50),
               comment=None,
               existing_comment='Type: inquiry, contact',
               existing_nullable=False)
    op.alter_column('meritto_crm_sync_audit', 'entity_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='ID of the inquiry or contact',
               existing_nullable=False)
    op.alter_column('meritto_crm_sync_audit', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20),
               comment=None,
               existing_comment='pending, success, failed, retrying',
               existing_nullable=False)
    op.alter_column('meritto_crm_sync_audit', 'attempt_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('meritto_crm_sync_audit', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('meritto_crm_sync_audit', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_index('idx_meritto_created_at', table_name='meritto_crm_sync_audit')
    op.drop_index('idx_meritto_email', table_name='meritto_crm_sync_audit')
    op.drop_index('idx_meritto_entity_type_id', table_name='meritto_crm_sync_audit')
    op.drop_index('idx_meritto_status', table_name='meritto_crm_sync_audit')
    op.create_index(op.f('ix_meritto_crm_sync_audit_created_at'), 'meritto_crm_sync_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_meritto_crm_sync_audit_entity_email'), 'meritto_crm_sync_audit', ['entity_email'], unique=False)
    op.create_index(op.f('ix_meritto_crm_sync_audit_id'), 'meritto_crm_sync_audit', ['id'], unique=False)
    op.create_index(op.f('ix_meritto_crm_sync_audit_status'), 'meritto_crm_sync_audit', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meritto_crm_sync_audit_status'), table_name='meritto_crm_sync_audit')
    op.drop_index(op.f('ix_meritto_crm_sync_audit_id'), table_name='meritto_crm_sync_audit')
    op.drop_index(op.f('ix_meritto_crm_sync_audit_entity_email'), table_name='meritto_crm_sync_audit')
    op.drop_index(op.f('ix_meritto_crm_sync_audit_created_at'), table_name='meritto_crm_sync_audit')
    op.create_index('idx_meritto_status', 'meritto_crm_sync_audit', ['status'], unique=False)
    op.create_index('idx_meritto_entity_type_id', 'meritto_crm_sync_audit', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_meritto_email', 'meritto_crm_sync_audit', ['entity_email'], unique=False)
    op.create_index('idx_meritto_created_at', 'meritto_crm_sync_audit', ['created_at'], unique=False)
    op.alter_column('meritto_crm_sync_audit', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('meritto_crm_sync_audit', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('meritto_crm_sync_audit', 'attempt_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('meritto_crm_sync_audit', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20),
               comment='pending, success, failed, retrying',
               existing_nullable=False)
    op.alter_column('meritto_crm_sync_audit', 'entity_id',
               existing_type=mysql.INTEGER(),
               comment='ID of the inquiry or contact',
               existing_nullable=False)
    op.alter_column('meritto_crm_sync_audit', 'entity_type',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=50),
               comment='Type: inquiry, contact',
               existing_nullable=False)
    # ### end Alembic commands ###
